Fix TypeError
python-livereload's API is changed in v2.4.1.
'ignore' keyword is added to Watcher#watch().
This change brings about TypeError in sphinx-autobuild.

$ sphinx-autobuild -b singlehtml source build/singlehtml
Traceback (most recent call last):
  File "/Users/amedama/.virtualenvs/sphinx-ab/bin/sphinx-autobuild", line 11, in <module>
    sys.exit(main())
  File "/Users/amedama/.virtualenvs/sphinx-ab/lib/python3.5/site-packages/sphinx_autobuild/__init__.py", line 280, in main
    server.watch(srcdir, builder)
  File "/Users/amedama/.virtualenvs/sphinx-ab/lib/python3.5/site-packages/livereload/server.py", line 203, in watch
    self.watcher.watch(filepath, func, delay, ignore=ignore)
TypeError: watch() got an unexpected keyword argument 'ignore'

Therefore, we should add the parameter to LivereloadWatchdogWatcher#watch().